### ISSUE TITLE
Issue regarding location permission

### ISSUE THREAD

**Issue by Puspha22** [muyiwexy/Leafletmap#1]
Since the SetInterval is set to 5 seconds, the browser is popping up "The file wants to know your location" every 5 seconds. Even allowing the permission as forever doesn't work. Maybe there is some alternative.

**Comment by Puspha22** [comment]
I solved this problem by updating the leaflet version to the latest.

**Comment by muyiwexy** [comment]
Ohh that's great, I didn't experience the issue on my end but I'm glad you figured it out. Kindly rate the article and let me know if you have any further opinion on it
